# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_locations <- function(B) {
    .Call(`_rsetse_get_locations`, B)
}

all_dims_one_loc <- function(ten_mat, kvect, Hvect, dvect, dzvect, net_tension) {
    .Call(`_rsetse_all_dims_one_loc`, ten_mat, kvect, Hvect, dvect, dzvect, net_tension)
}

core_while_loop_sparse_cpp <- function(max_iter, sample, network_dynamics, elevation, non_empty_t_vect, non_empty_vect, dvect, velocity, acceleration, static_force, force, net_tension, tstep, ten_mat, kvect, mass, dynamic_reset, tstep_change, net_force, coef_drag, static_limit, tol, timeshift, noisy_termination, verbose_reporting) {
    .Call(`_rsetse_core_while_loop_sparse_cpp`, max_iter, sample, network_dynamics, elevation, non_empty_t_vect, non_empty_vect, dvect, velocity, acceleration, static_force, force, net_tension, tstep, ten_mat, kvect, mass, dynamic_reset, tstep_change, net_force, coef_drag, static_limit, tol, timeshift, noisy_termination, verbose_reporting)
}

all_dims_one_loc_dense <- function(ten_mat, kvect, Hvect, dvect, dzvect, net_tension, non_empty_index_vec) {
    .Call(`_rsetse_all_dims_one_loc_dense`, ten_mat, kvect, Hvect, dvect, dzvect, net_tension, non_empty_index_vec)
}

core_while_loop_dense_cpp <- function(max_iter, sample, network_dynamics, elevation, non_empty_t_vect, non_empty_vect, dvect, velocity, acceleration, static_force, force, net_tension, tstep, ten_mat, kvect, mass, dynamic_reset, tstep_change, net_force, coef_drag, static_limit, tol, non_empty_index_vec, timeshift, noisy_termination, verbose_reporting) {
    .Call(`_rsetse_core_while_loop_dense_cpp`, max_iter, sample, network_dynamics, elevation, non_empty_t_vect, non_empty_vect, dvect, velocity, acceleration, static_force, force, net_tension, tstep, ten_mat, kvect, mass, dynamic_reset, tstep_change, net_force, coef_drag, static_limit, tol, non_empty_index_vec, timeshift, noisy_termination, verbose_reporting)
}

